### ISSUE TITLE
keyError

### ISSUE THREAD

**Issue by fangzhixiang** [Jwicaksana/FedMix#1]
I'm glad to see the job you shared. Can I ask how to solve this problem？
![9384894cf4303b55b32b23999f0f823](https://github.com/Jwicaksana/FedMix/assets/138980843/8a7e987c-0b23-42b7-8a41-7b4e3837c2b6)
![image](https://github.com/Jwicaksana/FedMix/assets/138980843/c01cfd2b-0eec-47e6-95ed-cc28e36ae331)
@Jwicaksana

**Comment by Jwicaksana** [comment]
Thanks for checking @fangzhixiang , the simplest way is to (in the csv):
1. insert a row above row 1 
2. add dataset to H1


![Screenshot 2023-07-27 at 5 31 09 PM](https://github.com/Jwicaksana/FedMix/assets/17629669/5f8cb542-c3a6-43c6-97c6-823ebc84e260)

**Comment by fangzhixiang** [comment]
Thank you very much for your answer. It has been very helpful to me.
